version: 0.1.0
appName: LockBox
device:
  os:
database:
  schema: lockbox_account_data
  username:
  connection:
    poolSize: 10
    # Seconds
    timeout: 30
    connectionTimeout: 30
    # minutes
    lifetime: 30
